"""add ai symptom assessments

Revision ID: 03e4b078bdc6
Revises: 1d8a27984c95
Create Date: 2026-09-19 18:06:55.174987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03e4b078bdc6'
down_revision: Union[str, Sequence[str], None] = '1d8a27984c95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_symptom_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('symptoms_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('possible_conditions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_specialty_id', sa.Integer(), nullable=False),
    sa.Column('recommended_specialty_code', sa.String(length=100), nullable=False),
    sa.Column('specialty_reason', sa.Text(), nullable=False),
    sa.Column('urgency', sa.String(length=20), nullable=False),
    sa.Column('red_flags_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('safety_message', sa.Text(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=150), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recommended_specialty_id'], ['specialties.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_symptom_assessments_created_at', 'ai_symptom_assessments', ['created_at'], unique=False)
    op.create_index('ix_ai_symptom_assessments_patient_id', 'ai_symptom_assessments', ['patient_id'], unique=False)
    op.create_index('ix_ai_symptom_assessments_specialty_id', 'ai_symptom_assessments', ['recommended_specialty_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_symptom_assessments_specialty_id', table_name='ai_symptom_assessments')
    op.drop_index('ix_ai_symptom_assessments_patient_id', table_name='ai_symptom_assessments')
    op.drop_index('ix_ai_symptom_assessments_created_at', table_name='ai_symptom_assessments')
    op.drop_table('ai_symptom_assessments')
    # ### end Alembic commands ###
