"""add activity routine module

Revision ID: 0f8bc1158ba9
Revises: 4391bcb21ace
Create Date: 2026-09-19 20:20:10.177203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f8bc1158ba9'
down_revision: Union[str, Sequence[str], None] = '4391bcb21ace'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.String(length=40), nullable=False),
    sa.Column('activity_level', sa.String(length=30), nullable=False),
    sa.Column('available_minutes_per_day', sa.Integer(), nullable=False),
    sa.Column('sleep_hours_snapshot', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=30), server_default='RULE_BASED', nullable=False),
    sa.Column('safety_message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_plans_created_at', 'activity_plans', ['created_at'], unique=False)
    op.create_index('ix_activity_plans_patient_id', 'activity_plans', ['patient_id'], unique=False)
    op.create_index('uq_activity_plans_one_active_per_patient', 'activity_plans', ['patient_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('activity_plan_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('activity_plan_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_value', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('target_unit', sa.String(length=30), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_plan_id'], ['activity_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_plan_items_plan_id', 'activity_plan_items', ['activity_plan_id'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('activity_plan_item_id', sa.UUID(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('actual_value', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_plan_item_id'], ['activity_plan_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_plan_item_id', 'log_date', name='uq_activity_log_item_date')
    )
    op.create_index('ix_activity_logs_patient_date', 'activity_logs', ['patient_id', 'log_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_logs_patient_date', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('ix_activity_plan_items_plan_id', table_name='activity_plan_items')
    op.drop_table('activity_plan_items')
    op.drop_index('uq_activity_plans_one_active_per_patient', table_name='activity_plans', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_activity_plans_patient_id', table_name='activity_plans')
    op.drop_index('ix_activity_plans_created_at', table_name='activity_plans')
    op.drop_table('activity_plans')
    # ### end Alembic commands ###
