"""enforce one primary specialty per doctor

Revision ID: 14a1d3612b50
Revises: 2d7bf8fb0fbe
Create Date: 2026-09-17 20:57:37.107761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14a1d3612b50'
down_revision: Union[str, Sequence[str], None] = '2d7bf8fb0fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_doctor_primary_specialty', 'doctor_specialties', ['doctor_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_doctor_primary_specialty', table_name='doctor_specialties', postgresql_where=sa.text('is_primary = true'))
    # ### end Alembic commands ###
