"""add admin facilities module

Revision ID: 278f7e40877a
Revises: 4224535254cc
Create Date: 2026-09-21 18:09:52.992090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278f7e40877a'
down_revision: Union[str, Sequence[str], None] = '4224535254cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('healthcare_facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('facility_type', sa.String(length=40), nullable=False),
    sa.Column('address_line_1', sa.String(length=200), nullable=True),
    sa.Column('address_line_2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=24), nullable=True),
    sa.Column('country', sa.String(length=100), server_default=sa.text("'India'"), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("facility_type IN ('HOSPITAL', 'CLINIC', 'PHARMACY', 'DIAGNOSTIC_CENTER')", name='ck_healthcare_facilities_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_healthcare_facilities_city'), 'healthcare_facilities', ['city'], unique=False)
    op.create_index(op.f('ix_healthcare_facilities_state'), 'healthcare_facilities', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_healthcare_facilities_state'), table_name='healthcare_facilities')
    op.drop_index(op.f('ix_healthcare_facilities_city'), table_name='healthcare_facilities')
    op.drop_table('healthcare_facilities')
    # ### end Alembic commands ###
