"""set doctor accepting patients default false

Revision ID: 2d7bf8fb0fbe
Revises: 8490c4b92225
Create Date: 2026-09-17 20:52:47.277235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7bf8fb0fbe'
down_revision: Union[str, Sequence[str], None] = '8490c4b92225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
