"""add diet plans

Revision ID: 4391bcb21ace
Revises: 03e4b078bdc6
Create Date: 2026-09-19 18:44:40.060559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4391bcb21ace'
down_revision: Union[str, Sequence[str], None] = '03e4b078bdc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diet_plans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('activity_level', sa.String(length=30), nullable=False),
    sa.Column('diet_preference', sa.String(length=30), nullable=False),
    sa.Column('goal', sa.String(length=30), nullable=False),
    sa.Column('bmi', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('estimated_daily_calories', sa.Integer(), nullable=False),
    sa.Column('water_target_ml', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=30), server_default='RULE_BASED', nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('calculation_note', sa.Text(), nullable=False),
    sa.Column('safety_message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diet_plans_created_at', 'diet_plans', ['created_at'], unique=False)
    op.create_index('ix_diet_plans_patient_id', 'diet_plans', ['patient_id'], unique=False)
    op.create_index('uq_diet_plans_one_active_per_patient', 'diet_plans', ['patient_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    op.create_table('diet_plan_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('diet_plan_id', sa.UUID(), nullable=False),
    sa.Column('meal_type', sa.String(length=30), nullable=False),
    sa.Column('food_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.String(length=150), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diet_plan_id'], ['diet_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diet_plan_items_diet_plan_id', 'diet_plan_items', ['diet_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_diet_plan_items_diet_plan_id', table_name='diet_plan_items')
    op.drop_table('diet_plan_items')
    op.drop_index('uq_diet_plans_one_active_per_patient', table_name='diet_plans', postgresql_where=sa.text('is_active = true'))
    op.drop_index('ix_diet_plans_patient_id', table_name='diet_plans')
    op.drop_index('ix_diet_plans_created_at', table_name='diet_plans')
    op.drop_table('diet_plans')
    # ### end Alembic commands ###
