"""add medication reminder system

Revision ID: 4a370f9eb87a
Revises: 6a5dd75bf83b
Create Date: 2026-09-16 21:28:56.555897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a370f9eb87a'
down_revision: Union[str, Sequence[str], None] = '6a5dd75bf83b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_medications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('medicine_id', sa.UUID(), nullable=True),
    sa.Column('medicine_name', sa.String(length=255), nullable=False),
    sa.Column('prescription_item_id', sa.UUID(), nullable=True),
    sa.Column('source', sa.Enum('PRESCRIPTION', 'MANUAL', name='medication_source'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'STOPPED', name='medication_status'), server_default='ACTIVE', nullable=False),
    sa.Column('strength', sa.String(length=100), nullable=True),
    sa.Column('dose', sa.String(length=100), nullable=True),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='ck_patient_medication_dates'),
    sa.ForeignKeyConstraint(['medicine_id'], ['medicines.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_item_id'], ['prescription_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prescription_item_id', name='uq_patient_medication_prescription_item')
    )
    op.create_index(op.f('ix_patient_medications_medicine_id'), 'patient_medications', ['medicine_id'], unique=False)
    op.create_index(op.f('ix_patient_medications_patient_id'), 'patient_medications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_medications_source'), 'patient_medications', ['source'], unique=False)
    op.create_index(op.f('ix_patient_medications_status'), 'patient_medications', ['status'], unique=False)
    op.create_table('medication_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_medication_id', sa.UUID(), nullable=False),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Kolkata', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_medication_id'], ['patient_medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_medication_id', 'time_of_day', name='uq_medication_schedule_time')
    )
    op.create_index(op.f('ix_medication_schedules_patient_medication_id'), 'medication_schedules', ['patient_medication_id'], unique=False)
    op.create_table('medication_adherence_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_medication_id', sa.UUID(), nullable=False),
    sa.Column('medication_schedule_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('TAKEN', 'MISSED', 'SKIPPED', 'LATE', name='adherence_status'), nullable=False),
    sa.Column('taken_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medication_schedule_id'], ['medication_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_medication_id'], ['patient_medications.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('medication_schedule_id', 'scheduled_for', name='uq_medication_adherence_occurrence')
    )
    op.create_index(op.f('ix_medication_adherence_logs_medication_schedule_id'), 'medication_adherence_logs', ['medication_schedule_id'], unique=False)
    op.create_index(op.f('ix_medication_adherence_logs_patient_medication_id'), 'medication_adherence_logs', ['patient_medication_id'], unique=False)
    op.create_index(op.f('ix_medication_adherence_logs_scheduled_for'), 'medication_adherence_logs', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_medication_adherence_logs_status'), 'medication_adherence_logs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medication_adherence_logs_status'), table_name='medication_adherence_logs')
    op.drop_index(op.f('ix_medication_adherence_logs_scheduled_for'), table_name='medication_adherence_logs')
    op.drop_index(op.f('ix_medication_adherence_logs_patient_medication_id'), table_name='medication_adherence_logs')
    op.drop_index(op.f('ix_medication_adherence_logs_medication_schedule_id'), table_name='medication_adherence_logs')
    op.drop_table('medication_adherence_logs')
    op.drop_index(op.f('ix_medication_schedules_patient_medication_id'), table_name='medication_schedules')
    op.drop_table('medication_schedules')
    op.drop_index(op.f('ix_patient_medications_status'), table_name='patient_medications')
    op.drop_index(op.f('ix_patient_medications_source'), table_name='patient_medications')
    op.drop_index(op.f('ix_patient_medications_patient_id'), table_name='patient_medications')
    op.drop_index(op.f('ix_patient_medications_medicine_id'), table_name='patient_medications')
    op.drop_table('patient_medications')
    # ### end Alembic commands ###
