"""add medical access grants

Revision ID: 6a5dd75bf83b
Revises: cde0e889e585
Create Date: 2026-09-16 20:55:46.403293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5dd75bf83b'
down_revision: Union[str, Sequence[str], None] = 'cde0e889e585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_access_grants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Enum('FULL_HISTORY', 'APPOINTMENT_ONLY', name='access_scope'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id', 'doctor_id', name='uq_medical_access_patient_doctor')
    )
    op.create_index(op.f('ix_medical_access_grants_doctor_id'), 'medical_access_grants', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_medical_access_grants_patient_id'), 'medical_access_grants', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_access_grants_patient_id'), table_name='medical_access_grants')
    op.drop_index(op.f('ix_medical_access_grants_doctor_id'), table_name='medical_access_grants')
    op.drop_table('medical_access_grants')
    # ### end Alembic commands ###
