"""add preventive health articles

Revision ID: 7b10054ac123
Revises: 0f8bc1158ba9
Create Date: 2026-09-20 19:24:56.198484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7b10054ac123'
down_revision: Union[str, Sequence[str], None] = '0f8bc1158ba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('key_points_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('professional_advice_note', sa.Text(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='PUBLISHED', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_health_articles_category', 'health_articles', ['category'], unique=False)
    op.create_index('ix_health_articles_published_at', 'health_articles', ['published_at'], unique=False)
    op.create_index('ix_health_articles_status', 'health_articles', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_health_articles_status', table_name='health_articles')
    op.drop_index('ix_health_articles_published_at', table_name='health_articles')
    op.drop_index('ix_health_articles_category', table_name='health_articles')
    op.drop_table('health_articles')
    # ### end Alembic commands ###
