"""add clinical encounters

Revision ID: a71df1a37751
Revises: 8293d07a580d
Create Date: 2026-09-15 22:54:26.023323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a71df1a37751'
down_revision: Union[str, Sequence[str], None] = '8293d07a580d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encounters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('encounter_type', sa.Enum('IN_PERSON', 'ONLINE', 'EMERGENCY', 'FOLLOW_UP', name='encounter_type'), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('subjective_notes', sa.Text(), nullable=True),
    sa.Column('objective_notes', sa.Text(), nullable=True),
    sa.Column('assessment_notes', sa.Text(), nullable=True),
    sa.Column('plan_notes', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id', name='uq_encounter_appointment')
    )
    op.create_index(op.f('ix_encounters_appointment_id'), 'encounters', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_encounters_doctor_id'), 'encounters', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_doctor_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_appointment_id'), table_name='encounters')
    op.drop_table('encounters')
    # ### end Alembic commands ###
