"""add encounter diagnoses

Revision ID: ce787c084604
Revises: a71df1a37751
Create Date: 2026-09-16 12:04:43.257466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce787c084604'
down_revision: Union[str, Sequence[str], None] = 'a71df1a37751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_code'), 'diagnoses', ['code'], unique=True)
    op.create_index(op.f('ix_diagnoses_name'), 'diagnoses', ['name'], unique=True)
    op.create_table('encounter_diagnoses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_id', sa.UUID(), nullable=False),
    sa.Column('diagnosis_type', sa.Enum('PRIMARY', 'SECONDARY', 'SUSPECTED', name='diagnosis_type'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnoses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encounter_id', 'diagnosis_id', 'diagnosis_type', name='uq_encounter_diagnosis_type')
    )
    op.create_index(op.f('ix_encounter_diagnoses_created_by_user_id'), 'encounter_diagnoses', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_encounter_diagnoses_diagnosis_id'), 'encounter_diagnoses', ['diagnosis_id'], unique=False)
    op.create_index(op.f('ix_encounter_diagnoses_encounter_id'), 'encounter_diagnoses', ['encounter_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encounter_diagnoses_encounter_id'), table_name='encounter_diagnoses')
    op.drop_index(op.f('ix_encounter_diagnoses_diagnosis_id'), table_name='encounter_diagnoses')
    op.drop_index(op.f('ix_encounter_diagnoses_created_by_user_id'), table_name='encounter_diagnoses')
    op.drop_table('encounter_diagnoses')
    op.drop_index(op.f('ix_diagnoses_name'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_code'), table_name='diagnoses')
    op.drop_table('diagnoses')
    # ### end Alembic commands ###
