"""add emergency sos module

Revision ID: e33507c0d40c
Revises: 7b10054ac123
Create Date: 2026-09-21 14:51:15.182643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e33507c0d40c'
down_revision: Union[str, Sequence[str], None] = '7b10054ac123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sos_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='TRIGGERED', nullable=False),
    sa.Column('share_location', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('location_accuracy_m', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('emergency_contact_name', sa.String(length=120), nullable=True),
    sa.Column('emergency_contact_phone', sa.String(length=32), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('TRIGGERED', 'ACKNOWLEDGED', 'RESOLVED', 'CANCELLED')", name='ck_sos_events_status'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sos_events_patient_id'), 'sos_events', ['patient_id'], unique=False)
    op.create_index('ix_sos_events_patient_status', 'sos_events', ['patient_id', 'status'], unique=False)
    op.create_index('ix_sos_events_triggered_at', 'sos_events', ['triggered_at'], unique=False)
    op.create_index('uq_sos_events_patient_active', 'sos_events', ['patient_id'], unique=True, postgresql_where=sa.text("status IN ('TRIGGERED', 'ACKNOWLEDGED')"))
    op.create_table('sos_event_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sos_event_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sos_event_id'], ['sos_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sos_event_actions_event_created', 'sos_event_actions', ['sos_event_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_sos_event_actions_sos_event_id'), 'sos_event_actions', ['sos_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sos_event_actions_sos_event_id'), table_name='sos_event_actions')
    op.drop_index('ix_sos_event_actions_event_created', table_name='sos_event_actions')
    op.drop_table('sos_event_actions')
    op.drop_index('uq_sos_events_patient_active', table_name='sos_events', postgresql_where=sa.text("status IN ('TRIGGERED', 'ACKNOWLEDGED')"))
    op.drop_index('ix_sos_events_triggered_at', table_name='sos_events')
    op.drop_index('ix_sos_events_patient_status', table_name='sos_events')
    op.drop_index(op.f('ix_sos_events_patient_id'), table_name='sos_events')
    op.drop_table('sos_events')
    # ### end Alembic commands ###
