"""add doctor availability

Revision ID: e5c18ae7670f
Revises: 287e6f183786
Create Date: 2026-09-15 17:27:02.329698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5c18ae7670f'
down_revision: Union[str, Sequence[str], None] = '287e6f183786'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doctor_availability_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default='Asia/Kolkata', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='ck_availability_day_of_week'),
    sa.CheckConstraint('end_time > start_time', name='ck_availability_time_range'),
    sa.CheckConstraint('slot_duration_minutes > 0', name='ck_slot_duration_positive'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_availability_rules_doctor_id'), 'doctor_availability_rules', ['doctor_id'], unique=False)
    op.create_table('doctor_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'HELD', 'BOOKED', 'BLOCKED', name='slot_status'), server_default='AVAILABLE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at > start_at', name='ck_doctor_slot_range'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doctor_id', 'start_at', name='uq_doctor_slot_start')
    )
    op.create_index(op.f('ix_doctor_slots_doctor_id'), 'doctor_slots', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_slots_start_at'), 'doctor_slots', ['start_at'], unique=False)
    op.create_index(op.f('ix_doctor_slots_status'), 'doctor_slots', ['status'], unique=False)
    op.create_table('doctor_time_off',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doctor_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_at > start_at', name='ck_doctor_time_off_range'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_time_off_doctor_id'), 'doctor_time_off', ['doctor_id'], unique=False)
    op.create_table('doctor_slot_status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.Enum('AVAILABLE', 'HELD', 'BOOKED', 'BLOCKED', name='slot_status'), nullable=True),
    sa.Column('new_status', sa.Enum('AVAILABLE', 'HELD', 'BOOKED', 'BLOCKED', name='slot_status'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['doctor_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_slot_status_history_slot_id'), 'doctor_slot_status_history', ['slot_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doctor_slot_status_history_slot_id'), table_name='doctor_slot_status_history')
    op.drop_table('doctor_slot_status_history')
    op.drop_index(op.f('ix_doctor_time_off_doctor_id'), table_name='doctor_time_off')
    op.drop_table('doctor_time_off')
    op.drop_index(op.f('ix_doctor_slots_status'), table_name='doctor_slots')
    op.drop_index(op.f('ix_doctor_slots_start_at'), table_name='doctor_slots')
    op.drop_index(op.f('ix_doctor_slots_doctor_id'), table_name='doctor_slots')
    op.drop_table('doctor_slots')
    op.drop_index(op.f('ix_doctor_availability_rules_doctor_id'), table_name='doctor_availability_rules')
    op.drop_table('doctor_availability_rules')
    # ### end Alembic commands ###
