"""add health tracking

Revision ID: fde4bbdb9712
Revises: 4a370f9eb87a
Create Date: 2026-09-17 19:02:41.350875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde4bbdb9712'
down_revision: Union[str, Sequence[str], None] = '4a370f9eb87a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('health_metric_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('primary_label', sa.String(length=100), nullable=False),
    sa.Column('primary_unit', sa.String(length=50), nullable=False),
    sa.Column('secondary_label', sa.String(length=100), nullable=True),
    sa.Column('secondary_unit', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_metric_types_code'), 'health_metric_types', ['code'], unique=True)
    op.create_table('health_measurements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('metric_type_id', sa.Integer(), nullable=False),
    sa.Column('value_primary', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('value_secondary', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'DEVICE', 'IMPORTED', name='metric_source'), server_default='MANUAL', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('value_primary >= 0', name='ck_health_measurement_primary_positive'),
    sa.CheckConstraint('value_secondary IS NULL OR value_secondary >= 0', name='ck_health_measurement_secondary_positive'),
    sa.ForeignKeyConstraint(['metric_type_id'], ['health_metric_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_measurements_measured_at'), 'health_measurements', ['measured_at'], unique=False)
    op.create_index(op.f('ix_health_measurements_metric_type_id'), 'health_measurements', ['metric_type_id'], unique=False)
    op.create_index(op.f('ix_health_measurements_patient_id'), 'health_measurements', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_health_measurements_patient_id'), table_name='health_measurements')
    op.drop_index(op.f('ix_health_measurements_metric_type_id'), table_name='health_measurements')
    op.drop_index(op.f('ix_health_measurements_measured_at'), table_name='health_measurements')
    op.drop_table('health_measurements')
    op.drop_index(op.f('ix_health_metric_types_code'), table_name='health_metric_types')
    op.drop_table('health_metric_types')
    # ### end Alembic commands ###
